language: node_js
node_js:
  - '0.10'
before_install:
  - ruby -v
  - gem install bundler
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-drupal-theme' ]; then cd .. && eval "mv $currentfolder generator-drupal-theme" && cd generator-drupal-theme; fi
